# Form implementation generated from reading ui file 'select_file_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Select(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 334)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_file_wind = QtWidgets.QTextEdit(parent=Form)
        self.select_file_wind.setObjectName("select_file_wind")
        self.verticalLayout.addWidget(self.select_file_wind)
        self.select_file = QtWidgets.QPushButton(parent=Form)
        self.select_file.setObjectName("select_file")
        self.verticalLayout.addWidget(self.select_file)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.conf_comboBox = QtWidgets.QComboBox(parent=Form)
        self.conf_comboBox.setObjectName("conf_comboBox")
        self.verticalLayout.addWidget(self.conf_comboBox)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.conf = QtWidgets.QLineEdit(parent=Form)
        self.conf.setObjectName("conf")
        self.verticalLayout.addWidget(self.conf)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.close = QtWidgets.QPushButton(parent=Form)
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.next = QtWidgets.QPushButton(parent=Form)
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.select_file.setText(_translate("Form", "Выбрать файл"))
        self.label.setText(_translate("Form", "Или"))
        self.conf.setPlaceholderText(_translate("Form", "Участие"))
        self.close.setText(_translate("Form", "Отменить"))
        self.next.setText(_translate("Form", "Далее ->"))

